apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: levl-ingress
  namespace: levl
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: levl-levl-strip-be@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - secretName: levl-tls
  rules:
    - http:
        paths:
          - path: /be
            pathType: Prefix
            backend:
              service:
                name: levl-app
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: levl-strip-be
  namespace: levl
spec:
  stripPrefix:
    prefixes:
      - /be
