apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: levl-media
  namespace: levl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: levl-local
  volumeName: levl-media-pv
  resources:
    requests:
      storage: 30Gi
